/* WARNING: Do not modify this file. */
/* This file is generated from config.mk */

#ifndef _CFG_GLOBAL_H_
#define _CFG_GLOBAL_H_

#include <linux/broadcom/cfg_global_defines.h>

/* Configuration from /home/ljj/work/scl8500/589x_Linux_4.4a_SDK/work/linux/target/configs/config.mk */
#undef CFG_GLOBAL_LINUX_VERSION 
#undef CFG_GLOBAL_LINUX_BASE_VERSION 
#undef CFG_GLOBAL_LINUX_PATCH_VERSION 
#undef CFG_GLOBAL_UDEV_SUPPORT 
#undef CFG_GLOBAL_UDEV_EXTRAS 
#undef CFG_GLOBAL_VLAN_SUPPORT 
#undef CFG_GLOBAL_ALSA_LIB_SUPPORT 
#undef CFG_GLOBAL_ALSA_UTIL_SUPPORT 
#undef CFG_GLOBAL_DLF_SUPPORT 
#undef CFG_GLOBAL_ELFCMP_SUPPORT 
#undef CFG_GLOBAL_IMGFIX_SUPPORT 
#undef CFG_GLOBAL_SIGNED_IMAGE_UNSUPPORTED 
#undef CFG_GLOBAL_SIGNED_IMAGE_NOKEY 
#undef CFG_GLOBAL_SIGNED_IMAGE_512KEY 
#undef CFG_GLOBAL_SIGNED_IMAGE_1024KEY 
#undef CFG_GLOBAL_BOOT1_SECURITY_SUPPORT 
#undef CFG_GLOBAL_BOOT1_SIGNED_IMAGE_TYPE 
#undef CFG_GLOBAL_IMAGE_TYPE 
#undef CFG_GLOBAL_BOOT1_ENCRYPT_TYPE 
#undef CFG_GLOBAL_IMAGE_TYPE_NORMAL 
#undef CFG_GLOBAL_IMAGE_TYPE_DEBUG 
#undef CFG_GLOBAL_ENCRYPT_TYPE_NO_ENCRYPT 
#undef CFG_GLOBAL_ENCRYPT_TYPE_AES_CBC_256 
#undef CFG_GLOBAL_BOOT2_DSA_KEY_SRC_OTP 
#undef CFG_GLOBAL_BOOT2_DSA_KEY_SRC_IMAGE 
#undef CFG_GLOBAL_BOOT2_DECRYPT_KEY_SRC_OTP 
#undef CFG_GLOBAL_BOOT2_DECRYPT_KEY_SRC_IMAGE 
#undef CFG_GLOBAL_BOOT2_SIGNED_IMAGE_TYPE 
#undef CFG_GLOBAL_BOOT2_DSA_SOURCE 
#undef CFG_GLOBAL_BOOT2_ENCRYPT_TYPE 
#undef CFG_GLOBAL_BOOT2_DECRYPT_KEY_SOURCE 
#undef CFG_GLOBAL_BOOT2_MACHINE_ID_ARGUMENT_SUPPORT 
#undef CFG_GLOBAL_CUSTOM_BOOT1_SUPPORT 
#undef CFG_GLOBAL_MICROWIN_SUPPORT 
#undef CFG_GLOBAL_MICROWIN_SCREEN_PIXTYPE 
#undef CFG_GLOBAL_OTA_ENABLE 
#undef CFG_GLOBAL_SWIG_SUPPORT 
#undef CFG_GLOBAL_TCL_SUPPORT 
#undef CFG_GLOBAL_VCHIQ_SUPPORT 
#undef CFG_GLOBAL_VIDEO_SUPPORT 
#undef CFG_GLOBAL_VIDEO_BOOT_FROM_KERNEL 
#undef CFG_GLOBAL_VC03_FRAME_BUFFER_ALPHA_OVERRIDE 
#undef CFG_GLOBAL_LIBEXPAT_SUPPORT 
#undef CFG_GLOBAL_STDCPP_SUPPORT 
#undef CFG_GLOBAL_UBI_SUPPORT 
#undef CFG_GLOBAL_NEWLIB_SUPPORT 
#undef CFG_GLOBAL_BRCM_BOOT0_SUPPORT 
#undef CFG_GLOBAL_BRCM_BOOT12_SUPPORT 
#undef CFG_GLOBAL_BRCM_MEMTEST_SUPPORT 
#undef CFG_GLOBAL_BRCM_FLASHTEST_SUPPORT 
#undef CFG_GLOBAL_U_BOOT_SUPPORT 
#undef CFG_GLOBAL_U_BOOT_VERSION 
#undef CFG_GLOBAL_U_BOOT_OVERRIDE 
#undef CFG_GLOBAL_BOOT_NAND_FLASH 
#undef CFG_GLOBAL_NAND_ERASESIZE 
#undef CFG_GLOBAL_NOR_ERASESIZE 
#undef CFG_GLOBAL_FLASH_SIZE_MB 
#undef CFG_GLOBAL_NAND_ECC_BCH_NUM_BYTES 
#undef CFG_GLOBAL_NAND_TWHR 
#undef CFG_GLOBAL_NAND_TCCS 
#undef CFG_GLOBAL_DELAY_NSEC_MULT 
#undef CFG_GLOBAL_DELAY_NSEC_DIV 
#undef CFG_GLOBAL_BUSYBOX_SUPPORT 
#undef CFG_GLOBAL_BUILD_BUSYBOX_SUPPORT 
#undef CFG_GLOBAL_BUSYBOX_VERSION 
#undef CFG_GLOBAL_DEBUG_TEST_SUPPORT 
#undef CFG_GLOBAL_DRIVER_TEST_SUPPORT 
#undef CFG_GLOBAL_FLASH_TEST_SUPPORT 
#undef CFG_GLOBAL_GPIO_SUPPORT 
#undef CFG_GLOBAL_HELLO_WORLD_SUPPORT 
#undef CFG_GLOBAL_KERNEL_HELLO_WORLD_SUPPORT 
#undef CFG_GLOBAL_HACKBENCH_SUPPORT 
#undef CFG_GLOBAL_MULTICAST_SENDER_SUPPORT 
#undef CFG_GLOBAL_MULTICAST_RECEIVER_SUPPORT 
#undef CFG_GLOBAL_HWCLOCK_SUPPORT 
#undef CFG_GLOBAL_I2C_SUPPORT 
#undef CFG_GLOBAL_MMDMA_SUPPORT 
#undef CFG_GLOBAL_OTP_SUPPORT 
#undef CFG_GLOBAL_BACKLIGHT_SUPPORT 
#undef CFG_GLOBAL_BLCTL_SUPPORT 
#undef CFG_GLOBAL_IOCMD_SUPPORT 
#undef CFG_GLOBAL_GREYBOX_SUPPORT 
#undef CFG_GLOBAL_INPUT_SUPPORT 
#undef CFG_GLOBAL_LCDCTL_SUPPORT 
#undef CFG_GLOBAL_FBCTL_SUPPORT 
#undef CFG_GLOBAL_DDCTL_SUPPORT 
#undef CFG_GLOBAL_SETSCHED_SUPPORT 
#undef CFG_GLOBAL_PMU_TEST_SUPPORT 
#undef CFG_GLOBAL_PHP_SUPPORT 
#undef CFG_GLOBAL_SERIAL_TEST_SUPPORT 
#undef CFG_GLOBAL_SHOW_SUPPORT 
#undef CFG_GLOBAL_SIM_SUPPORT 
#undef CFG_GLOBAL_UDP_TEST_SUPPORT 
#undef CFG_GLOBAL_TCP_TEST_SUPPORT 
#undef CFG_GLOBAL_VIDEO_TEST_SUPPORT 
#undef CFG_GLOBAL_IGMP_TEST_SUPPORT 
#undef CFG_GLOBAL_PTHREAD_BASIC_TEST_SUPPORT 
#undef CFG_GLOBAL_PTHREAD_COND_WAIT_TEST_SUPPORT 
#undef CFG_GLOBAL_SYSLOG_TEST_SUPPORT 
#undef CFG_GLOBAL_WATCHDOGD_SUPPORT 
#undef CFG_GLOBAL_PLAYIT_SUPPORT 
#undef CFG_GLOBAL_HEADSET_TEST_SUPPORT 
#undef CFG_GLOBAL_CRYPTO_TEST_SUPPORT 
#undef CFG_GLOBAL_SDC_TEST_SUPPORT 
#undef CFG_GLOBAL_APPLAUNCHER_SUPPORT 
#undef CFG_GLOBAL_PXCON_SUPPORT 
#undef CFG_GLOBAL_WLTOOL_SUPPORT 
#undef CFG_GLOBAL_BDLNA_SUPPORT 
#undef CFG_GLOBAL_GDB_SERVER_SUPPORT 
#undef CFG_GLOBAL_GDB_SUPPORT 
#undef CFG_GLOBAL_ETHTOOL_SUPPORT 
#undef CFG_GLOBAL_JPEG_SUPPORT 
#undef CFG_GLOBAL_LRZSZ_SUPPORT 
#undef CFG_GLOBAL_NTP_SUPPORT 
#undef CFG_GLOBAL_OPENSSL_SUPPORT 
#undef CFG_GLOBAL_OPENSSL_TEST_CORE 
#undef CFG_GLOBAL_OPENSSL_TEST 
#undef CFG_GLOBAL_8021X_SUPPLICANT_SUPPORT 
#undef CFG_GLOBAL_BUILD_WPA_SUPPLICANT_SUPPORT 
#undef CFG_GLOBAL_LIBRT_SUPPORT 
#undef CFG_GLOBAL_TCPDUMP_SUPPORT 
#undef CFG_GLOBAL_STRACE_SUPPORT 
#undef CFG_GLOBAL_SOCAT_SUPPORT 
#undef CFG_GLOBAL_FFMPEG_SUPPORT 
#undef CFG_GLOBAL_FAAD2_SUPPORT 
#undef CFG_GLOBAL_LIBBZ2_SUPPORT 
#undef CFG_GLOBAL_PKA_SUPPORT 
#undef CFG_GLOBAL_PKA_DRIVER_SUPPORT 
#undef CFG_GLOBAL_APM_TEST_SUPPORT 
#undef CFG_GLOBAL_I2C_TEST_SUPPORT 
#undef CFG_GLOBAL_I2S_TEST_SUPPORT 
#undef CFG_GLOBAL_SPU_TEST_SUPPORT 
#undef CFG_GLOBAL_PKA_TEST_SUPPORT 
#undef CFG_GLOBAL_CSP_TEST_SUPPORT 
#undef CFG_GLOBAL_DHD_ROMTERM_SUPPORT 
#undef CFG_GLOBAL_DHD_VERSION_TAG 
#undef CFG_GLOBAL_DHD_VARIANT 
#undef CFG_GLOBAL_DHD_NVRAM_TXT 
#undef CFG_GLOBAL_DHD_BIN 
#undef CFG_GLOBAL_SAMBA_SERVER_SUPPORT 
#undef CFG_GLOBAL_SAMBA_CLIENT_SUPPORT 
#undef CFG_GLOBAL_NFS_CLIENT_SUPPORT 
#undef CFG_GLOBAL_KGDB_SUPPORT 
#undef CFG_GLOBAL_S6A0069_SUPPORT 
#undef CFG_GLOBAL_MTDUTIL_HOST_SUPPORT 
#undef CFG_GLOBAL_TIMIDITY_SUPPORT 
#undef CFG_GLOBAL_SQLITE3_SUPPORT 
#undef CFG_GLOBAL_LINUX_RAM_SIZE 
#undef CFG_GLOBAL_RAM_START_RESERVED_SIZE 
#undef CFG_GLOBAL_RAM_BASE 
#undef CFG_GLOBAL_HALAUDIO_SUPPORT 
#undef CFG_GLOBAL_XCHG_COMMON_SUPPORT 
#undef CFG_GLOBAL_XCHG_DRIVERS_SUPPORT 
#undef CFG_GLOBAL_EEMBC_NET_SUPPORT 
#undef CFG_GLOBAL_EEMBC_DEN_SUPPORT 
#undef CFG_GLOBAL_EEMBC_JAVA_SUPPORT 
#undef CFG_GLOBAL_JAVA_SUPPORT 
#undef CFG_GLOBAL_ALSA_VOLUME_SUPPORT 
#undef CFG_GLOBAL_HOTKEY_SUPPORT 
#undef CFG_GLOBAL_BTE_SUPPORT 
#undef CFG_GLOBAL_PRIV_WMDRM_SUPPORT 
#undef CFG_GLOBAL_WIRED_ENET_SUPPORT 
#undef CFG_GLOBAL_TOUCHSCREEN_SUPPORT 
#undef CFG_GLOBAL_RTLSIM_SUPPORT 
#undef CFG_GLOBAL_VDEC_SUPPORT 
#undef CFG_GLOBAL_VDEC_DEMO_SUPPORT 
#undef CFG_GLOBAL_VDEC_TOOL_SUPPORT 
#undef CFG_GLOBAL_VC03_B0_MPHI_MINI 
#undef CFG_GLOBAL_VPMSCALED_SUPPORT 
#undef CFG_GLOBAL_VPMINTSTRESS_SUPPORT 
#undef CFG_GLOBAL_BROADWARE_NRT_SUPPORT 
#undef CFG_GLOBAL_FSTESTS_SUPPORT 
#undef CFG_GLOBAL_PTH_SUPPORT 
#undef CFG_GLOBAL_ECLIPSE_DBG_SUPPORT 
#undef CFG_GLOBAL_LDX_SUPPORT 
#undef CFG_GLOBAL_FEC_SUPPORT 
#undef CFG_GLOBAL_ECAN_TEST_SUPPORT 
#undef CFG_GLOBAL_VCP_SUPPORT 
#undef CFG_GLOBAL_VCP_VC03_DRIVER 
#undef CFG_GLOBAL_KERNEL_DEBUG_SUPPORT 
#undef CFG_GLOBAL_ROOT_FILE_SYSTEM 
#undef CFG_GLOBAL_ROOT_FILE_SYSTEM_READ_ONLY 
#undef CFG_GLOBAL_FILE_SYSTEM_JFFS2 
#undef CFG_GLOBAL_FILE_SYSTEM_CRAMFS 
#undef CFG_GLOBAL_FILE_SYSTEM_INITRAMFS 
#undef CFG_GLOBAL_NFSROOT_STRING 
#undef CFG_GLOBAL_FILE_SYSTEM_UBIFS 
#undef CFG_GLOBAL_JFFS2_SUMMARY_SUPPORT 
#undef CFG_GLOBAL_UIMAGE_SUPPORT 
#undef CFG_GLOBAL_PAD_ROOTFS_SIZE 
#undef CFG_GLOBAL_CURL_SUPPORT 
#undef CFG_GLOBAL_LIBICONV_SUPPORT 
#undef CFG_GLOBAL_GETTEXT_SUPPORT 
#undef CFG_GLOBAL_GLIB_SUPPORT 
#undef CFG_GLOBAL_ZLIB_SUPPORT 
#undef CFG_GLOBAL_FREETYPE_SUPPORT 
#undef CFG_GLOBAL_LIBXML2_SUPPORT 
#undef CFG_GLOBAL_FONTCONFIG_SUPPORT 
#undef CFG_GLOBAL_ATK_SUPPORT 
#undef CFG_GLOBAL_LIBPNG_SUPPORT 
#undef CFG_GLOBAL_DIRECTFB_SUPPORT 
#undef CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT 
#undef CFG_GLOBAL_DIRECTFB_FUSION_SUPPORT 
#undef CFG_GLOBAL_CAIRO_SUPPORT 
#undef CFG_GLOBAL_PANGO_SUPPORT 
#undef CFG_GLOBAL_GTK_SUPPORT 
#undef CFG_GLOBAL_READLINE_SUPPORT 
#undef CFG_GLOBAL_SQLITE_SUPPORT 
#undef CFG_GLOBAL_LIBGPG_EEROR_SUPPORT 
#undef CFG_GLOBAL_LIBGCRYPT_SUPPORT 
#undef CFG_GLOBAL_LIBXSLT_SUPPORT 
#undef CFG_GLOBAL_ICU_SUPPORT 
#undef CFG_GLOBAL_WEBKIT_SUPPORT 
#undef CFG_GLOBAL_BUILD_LOCAL_DIRECTFB 
#undef CFG_GLOBAL_BUILD_LOCAL_DEBUG 
#undef CFG_GLOBAL_CHIP_FAMILY 
#undef CFG_GLOBAL_TOOLCHAIN_VERSION 
#undef CFG_GLOBAL_LIBC_VERSION 
#undef CFG_GLOBAL_IPV6_SUPPORT 
#undef CFG_GLOBAL_IPERF_SUPPORT 
#undef CFG_GLOBAL_EMQBIT_BENCH_SUPPORT 
#undef CFG_GLOBAL_VDECAL_SUPPORT 
#undef CFG_GLOBAL_ADEC_SUPPORT 
#undef CFG_GLOBAL_ADECAL_SUPPORT 
#undef CFG_GLOBAL_DISPMANX_TESTER_SUPPORT 
#undef CFG_GLOBAL_LIBEDIT_SUPPORT 
#undef CFG_GLOBAL_LIBNCURSES_SUPPORT 
#undef CFG_GLOBAL_LIBTINFO_SUPPORT 
#undef CFG_GLOBAL_KERNEL_VARIANT 
#undef CFG_GLOBAL_KHRONOS_SAMPLE_APPS_SUPPORT 
#undef CFG_GLOBAL_VIDEO_2D_DEMO_APP_SUPPORT 
#undef CFG_GLOBAL_FUSE_SUPPORT 
#undef CFG_GLOBAL_BCMRING_HW_CRYPTO_SUPPORT 
#undef CFG_GLOBAL_SUSPEND_TO_RAM_SUPPORT 
#undef CFG_GLOBAL_MTDUTIL_TARGET_SUPPORT 
#undef CFG_GLOBAL_FLOAT_INTERCEPT 
#undef CFG_GLOBAL_FLOAT_PERF 
#undef CFG_GLOBAL_EVERY_SUPPORT 
#undef CFG_GLOBAL_ADD_TAR_TO_FS 
#undef CFG_GLOBAL_OPROFILE_SUPPORT 
#undef CFG_GLOBAL_RTC_SUPPORT 
#undef CFG_GLOBAL_CSX_SUPPORT 
#undef CFG_GLOBAL_HTOP_SUPPORT 
#undef CFG_GLOBAL_BSC_SUPPORT 
#undef CFG_GLOBAL_GVR_SUPPORT 
#undef CFG_GLOBAL_EPTRPC_SUPPORT 
#undef CFG_GLOBAL_EPT_SUPPORT 
#undef CFG_GLOBAL_EPT_WB_VOICE_DEVICES 
#undef CFG_GLOBAL_EPT_NB_VOICE_DEVICES 
#undef CFG_GLOBAL_EPT_VIDEO_DEVICES 
#undef CFG_GLOBAL_PARTITION 
#undef CFG_GLOBAL_MIC_CAL_APP_SUPPORT 
#undef CFG_GLOBAL_DROPBEAR_SUPPORT 
#undef CFG_GLOBAL_ETH_LED_TEST_SUPPORT 
#undef CFG_GLOBAL_FLAT_FILE_SUPPORT 
#undef CFG_GLOBAL_BOOT1_POST_SUPPORT 
#undef CFG_GLOBAL_BOOT2_POST_SUPPORT 
#undef CFG_GLOBAL_LCD_USES_PIFHW 
#undef CFG_GLOBAL_PCSC_SUPPORT 
#undef CFG_GLOBAL_VOIP_MAX_PACKET_SIZE 
#undef CFG_GLOBAL_AUDIO_SUPPORT_TOOLS_SUPPORT 
#undef CFG_GLOBAL_AUDIOTEST_SUPPORT 
#undef CFG_GLOBAL_VOCODER_TEST_SUPPORT 
#undef CFG_GLOBAL_BBL_IS_ENABLED 
#undef CFG_GLOBAL_BCM_BOOT_REL_FILES 
#undef CFG_GLOBAL_BCM_VCEB_REL_FILES 
#undef CFG_GLOBAL_BCM_VMCS_REL_FILES 
#undef CFG_GLOBAL_BCM_VMCS_ROOTFS 
#undef CFG_GLOBAL_BELLAGIO_SUPPORT 
#undef CFG_GLOBAL_BLUETOOTH_SUPPORT 
#undef CFG_GLOBAL_BOINGO_SUPPORT 
#undef CFG_GLOBAL_BOOT_WATCHDOG_SUPPORT 
#undef CFG_GLOBAL_BTPI_TEST_SUPPORT 
#undef CFG_GLOBAL_CHIP 
#undef CFG_GLOBAL_CPU 
#undef CFG_GLOBAL_CPU_ENDIAN 
#undef CFG_GLOBAL_ECAN_USE_SBAEC 
#undef CFG_GLOBAL_ENABLE_POWER_SAVINGS_MODE 
#undef CFG_GLOBAL_EPT_INBAND_TONE_ENABLE 
#undef CFG_GLOBAL_GE_TEST_SUPPORT 
#undef CFG_GLOBAL_GUI_DIRS 
#undef CFG_GLOBAL_GUI_SUPPORT 
#undef CFG_GLOBAL_HOOKSWITCH_SUPPORT 
#undef CFG_GLOBAL_IPTABLES_SUPPORT 
#undef CFG_GLOBAL_LCD_SIZE 
#undef CFG_GLOBAL_LDXKO_DIR_FOR_HAUSWARE_LIBS 
#undef CFG_GLOBAL_LDXKO_DIR_FOR_SUPPORT_LIBS 
#undef CFG_GLOBAL_LLDP_SUPPORT 
#undef CFG_GLOBAL_MPEG4_SUPPORT 
#undef CFG_GLOBAL_ONEPHONE_APP_SUPPORT 
#undef CFG_GLOBAL_PHONE_APP_SUPPORT 
#undef CFG_GLOBAL_RECONFIG_SUPPORT 
#undef CFG_GLOBAL_REDUNDANCY_SUPPORT 
#undef CFG_GLOBAL_SDC_CACHE_PAGE_SIZE 
#undef CFG_GLOBAL_SDC_ENABLE 
#undef CFG_GLOBAL_SDC_LOCATION 
#undef CFG_GLOBAL_SDC_PKA_PRIVATE_KEY1 
#undef CFG_GLOBAL_SDC_PKA_PRIVATE_KEY2 
#undef CFG_GLOBAL_SDC_PKA_PRIVATE_KEY3 
#undef CFG_GLOBAL_SDC_PKA_PRIVATE_KEY4 
#undef CFG_GLOBAL_SDC_SIZE 
#undef CFG_GLOBAL_SIMPLESIPPHONE_APP_SUPPORT 
#undef CFG_GLOBAL_SIP_SUPPORT 
#undef CFG_GLOBAL_SKYPE_SUPPORT 
#undef CFG_GLOBAL_SKYPE_VERSION 
#undef CFG_GLOBAL_STRESSTEST_SUPPORT 
#undef CFG_GLOBAL_STUN_CLIENT 
#undef CFG_GLOBAL_SW_VERSION 
#undef CFG_GLOBAL_TR69_SUPPORT 
#undef CFG_GLOBAL_VCHIQ_SUPPORT  
#undef CFG_GLOBAL_VIBRATOR_SUPPORT 
#undef CFG_GLOBAL_VIDEOCORE_GENERATION 
#undef CFG_GLOBAL_VIDEOCORE_PLATFORM 
#undef CFG_GLOBAL_VIDEOCORE_RELEASE 
#undef CFG_GLOBAL_VIDEOCORE_SDCARD_SUPPORT 
#undef CFG_GLOBAL_VIDEOCORE_TARGET 
#undef CFG_GLOBAL_VIDEOCORE_TEST_SUPPORT 
#undef CFG_GLOBAL_VIDEO_SPLASH 
#undef CFG_GLOBAL_WEBCONFIG_SUPPORT 
#undef CFG_GLOBAL_KHRONOS_THIRD_PARTY_APPS_SUPPORT 
#define CFG_GLOBAL_LINUX_VERSION   linux-2.6.27.18
#define CFG_GLOBAL_LINUX_BASE_VERSION  
#define CFG_GLOBAL_LINUX_PATCH_VERSION  
#define CFG_GLOBAL_UDEV_SUPPORT   1
#define CFG_GLOBAL_UDEV_EXTRAS   0
#define CFG_GLOBAL_VLAN_SUPPORT   0
#define CFG_GLOBAL_ALSA_LIB_SUPPORT   0
#define CFG_GLOBAL_ALSA_UTIL_SUPPORT   0
#define CFG_GLOBAL_DLF_SUPPORT   1
#define CFG_GLOBAL_ELFCMP_SUPPORT   1
#define CFG_GLOBAL_IMGFIX_SUPPORT   1
#define CFG_GLOBAL_SIGNED_IMAGE_UNSUPPORTED   0
#define CFG_GLOBAL_SIGNED_IMAGE_NOKEY   0x80
#define CFG_GLOBAL_SIGNED_IMAGE_512KEY   0x20
#define CFG_GLOBAL_SIGNED_IMAGE_1024KEY   0x30
#define CFG_GLOBAL_BOOT1_SECURITY_SUPPORT   0
#define CFG_GLOBAL_BOOT1_SIGNED_IMAGE_TYPE   0
#define CFG_GLOBAL_IMAGE_TYPE   0
#define CFG_GLOBAL_BOOT1_ENCRYPT_TYPE   CFG_GLOBAL_ENCRYPT_TYPE_NO_ENCRYPT
#define CFG_GLOBAL_IMAGE_TYPE_NORMAL   0x0
#define CFG_GLOBAL_IMAGE_TYPE_DEBUG   0x1
#define CFG_GLOBAL_ENCRYPT_TYPE_NO_ENCRYPT   0
#define CFG_GLOBAL_ENCRYPT_TYPE_AES_CBC_256   1
#define CFG_GLOBAL_BOOT2_DSA_KEY_SRC_OTP   0
#define CFG_GLOBAL_BOOT2_DSA_KEY_SRC_IMAGE   1
#define CFG_GLOBAL_BOOT2_DECRYPT_KEY_SRC_OTP   0
#define CFG_GLOBAL_BOOT2_DECRYPT_KEY_SRC_IMAGE   1
#define CFG_GLOBAL_BOOT2_SIGNED_IMAGE_TYPE   0
#define CFG_GLOBAL_BOOT2_DSA_SOURCE   CFG_GLOBAL_BOOT2_DSA_OTP
#define CFG_GLOBAL_BOOT2_ENCRYPT_TYPE   CFG_GLOBAL_ENCRYPT_TYPE_NO_ENCRYPT
#define CFG_GLOBAL_BOOT2_DECRYPT_KEY_SOURCE   CFG_GLOBAL_BOOT2_DECRYPT_KEY_SRC_OTP
#define CFG_GLOBAL_BOOT2_MACHINE_ID_ARGUMENT_SUPPORT   0
#define CFG_GLOBAL_CUSTOM_BOOT1_SUPPORT   0
#define CFG_GLOBAL_MICROWIN_SUPPORT   0
#define CFG_GLOBAL_MICROWIN_SCREEN_PIXTYPE   MWPF_TRUECOLOR565
#define CFG_GLOBAL_OTA_ENABLE   0
#define CFG_GLOBAL_SWIG_SUPPORT   0
#define CFG_GLOBAL_TCL_SUPPORT   0
#define CFG_GLOBAL_VCHIQ_SUPPORT   0
#define CFG_GLOBAL_VIDEO_SUPPORT   0
#define CFG_GLOBAL_VIDEO_BOOT_FROM_KERNEL   0
#define CFG_GLOBAL_VC03_FRAME_BUFFER_ALPHA_OVERRIDE   0
#define CFG_GLOBAL_LIBEXPAT_SUPPORT   0
#define CFG_GLOBAL_STDCPP_SUPPORT   0
#define CFG_GLOBAL_UBI_SUPPORT   0
#define CFG_GLOBAL_NEWLIB_SUPPORT   0
#define CFG_GLOBAL_BRCM_BOOT0_SUPPORT   0
#define CFG_GLOBAL_BRCM_BOOT12_SUPPORT   1
#define CFG_GLOBAL_BRCM_MEMTEST_SUPPORT   0
#define CFG_GLOBAL_BRCM_FLASHTEST_SUPPORT   0
#define CFG_GLOBAL_U_BOOT_SUPPORT   0
#define CFG_GLOBAL_U_BOOT_VERSION   u-boot-1.3.3
#define CFG_GLOBAL_U_BOOT_OVERRIDE   0
#define CFG_GLOBAL_BOOT_NAND_FLASH   1	 // default to boot from NAND flash
#define CFG_GLOBAL_NAND_ERASESIZE   0x4000
#define CFG_GLOBAL_NOR_ERASESIZE   0x20000
#define CFG_GLOBAL_FLASH_SIZE_MB   32
#define CFG_GLOBAL_NAND_ECC_BCH_NUM_BYTES   13
#define CFG_GLOBAL_NAND_TWHR   0
#define CFG_GLOBAL_NAND_TCCS   0
#define CFG_GLOBAL_DELAY_NSEC_MULT   1
#define CFG_GLOBAL_DELAY_NSEC_DIV   4
#define CFG_GLOBAL_BUSYBOX_SUPPORT   1
#define CFG_GLOBAL_BUILD_BUSYBOX_SUPPORT   0
#define CFG_GLOBAL_BUSYBOX_VERSION   busybox-1.15.3
#define CFG_GLOBAL_DEBUG_TEST_SUPPORT   0
#define CFG_GLOBAL_DRIVER_TEST_SUPPORT   0
#define CFG_GLOBAL_FLASH_TEST_SUPPORT   1
#define CFG_GLOBAL_GPIO_SUPPORT   1
#define CFG_GLOBAL_HELLO_WORLD_SUPPORT   0
#define CFG_GLOBAL_KERNEL_HELLO_WORLD_SUPPORT   0
#define CFG_GLOBAL_HACKBENCH_SUPPORT   0
#define CFG_GLOBAL_MULTICAST_SENDER_SUPPORT   0
#define CFG_GLOBAL_MULTICAST_RECEIVER_SUPPORT   0
#define CFG_GLOBAL_HWCLOCK_SUPPORT   0
#define CFG_GLOBAL_I2C_SUPPORT   0
#define CFG_GLOBAL_MMDMA_SUPPORT   0
#define CFG_GLOBAL_OTP_SUPPORT   0
#define CFG_GLOBAL_BACKLIGHT_SUPPORT   1
#define CFG_GLOBAL_BLCTL_SUPPORT   1
#define CFG_GLOBAL_IOCMD_SUPPORT   1
#define CFG_GLOBAL_GREYBOX_SUPPORT   0
#define CFG_GLOBAL_INPUT_SUPPORT   1
#define CFG_GLOBAL_LCDCTL_SUPPORT   1
#define CFG_GLOBAL_FBCTL_SUPPORT   0
#define CFG_GLOBAL_DDCTL_SUPPORT   0
#define CFG_GLOBAL_SETSCHED_SUPPORT   1
#define CFG_GLOBAL_PMU_TEST_SUPPORT   0
#define CFG_GLOBAL_PHP_SUPPORT   0
#define CFG_GLOBAL_SERIAL_TEST_SUPPORT   0
#define CFG_GLOBAL_SHOW_SUPPORT   0
#define CFG_GLOBAL_SIM_SUPPORT   0
#define CFG_GLOBAL_UDP_TEST_SUPPORT   0
#define CFG_GLOBAL_TCP_TEST_SUPPORT   0
#define CFG_GLOBAL_VIDEO_TEST_SUPPORT   0
#define CFG_GLOBAL_IGMP_TEST_SUPPORT   0
#define CFG_GLOBAL_PTHREAD_BASIC_TEST_SUPPORT   0
#define CFG_GLOBAL_PTHREAD_COND_WAIT_TEST_SUPPORT   0
#define CFG_GLOBAL_SYSLOG_TEST_SUPPORT   0
#define CFG_GLOBAL_WATCHDOGD_SUPPORT   1
#define CFG_GLOBAL_PLAYIT_SUPPORT   0
#define CFG_GLOBAL_HEADSET_TEST_SUPPORT   0
#define CFG_GLOBAL_CRYPTO_TEST_SUPPORT   0
#define CFG_GLOBAL_SDC_TEST_SUPPORT   0
#define CFG_GLOBAL_APPLAUNCHER_SUPPORT   0
#define CFG_GLOBAL_PXCON_SUPPORT   0
#define CFG_GLOBAL_WLTOOL_SUPPORT   0
#define CFG_GLOBAL_BDLNA_SUPPORT   0
#define CFG_GLOBAL_GDB_SERVER_SUPPORT   1
#define CFG_GLOBAL_GDB_SUPPORT   0
#define CFG_GLOBAL_ETHTOOL_SUPPORT   0
#define CFG_GLOBAL_JPEG_SUPPORT   0
#define CFG_GLOBAL_LRZSZ_SUPPORT   1
#define CFG_GLOBAL_NTP_SUPPORT   1
#define CFG_GLOBAL_OPENSSL_SUPPORT   0
#define CFG_GLOBAL_OPENSSL_TEST_CORE   0
#define CFG_GLOBAL_OPENSSL_TEST   0
#define CFG_GLOBAL_8021X_SUPPLICANT_SUPPORT   0
#define CFG_GLOBAL_BUILD_WPA_SUPPLICANT_SUPPORT   0
#define CFG_GLOBAL_LIBRT_SUPPORT   0
#define CFG_GLOBAL_TCPDUMP_SUPPORT   0
#define CFG_GLOBAL_STRACE_SUPPORT   0
#define CFG_GLOBAL_SOCAT_SUPPORT   0
#define CFG_GLOBAL_FFMPEG_SUPPORT   0
#define CFG_GLOBAL_FAAD2_SUPPORT   0
#define CFG_GLOBAL_LIBBZ2_SUPPORT   0
#define CFG_GLOBAL_PKA_SUPPORT   0
#define CFG_GLOBAL_PKA_DRIVER_SUPPORT   0
#define CFG_GLOBAL_APM_TEST_SUPPORT   0
#define CFG_GLOBAL_I2C_TEST_SUPPORT   0
#define CFG_GLOBAL_I2S_TEST_SUPPORT   0
#define CFG_GLOBAL_SPU_TEST_SUPPORT   0
#define CFG_GLOBAL_PKA_TEST_SUPPORT   0
#define CFG_GLOBAL_CSP_TEST_SUPPORT   0
#define CFG_GLOBAL_DHD_ROMTERM_SUPPORT   0
#define CFG_GLOBAL_DHD_VERSION_TAG   ROMTERM_REL_4_218_137
#define CFG_GLOBAL_DHD_VARIANT   BCM4329
#define CFG_GLOBAL_DHD_NVRAM_TXT   wl-nvram.txt
#define CFG_GLOBAL_DHD_BIN   sdio-g-cdc-full11n-reclaim-roml-wme.bin
#define CFG_GLOBAL_SAMBA_SERVER_SUPPORT   0
#define CFG_GLOBAL_SAMBA_CLIENT_SUPPORT   0
#define CFG_GLOBAL_NFS_CLIENT_SUPPORT   1
#define CFG_GLOBAL_KGDB_SUPPORT   0
#define CFG_GLOBAL_S6A0069_SUPPORT   0
#define CFG_GLOBAL_MTDUTIL_HOST_SUPPORT   0
#define CFG_GLOBAL_TIMIDITY_SUPPORT   0
#define CFG_GLOBAL_SQLITE3_SUPPORT   0
#define CFG_GLOBAL_LINUX_RAM_SIZE   0x2000000
#define CFG_GLOBAL_RAM_START_RESERVED_SIZE   0
#define CFG_GLOBAL_RAM_BASE   0x80000000
#define CFG_GLOBAL_HALAUDIO_SUPPORT   0
#define CFG_GLOBAL_XCHG_COMMON_SUPPORT   0
#define CFG_GLOBAL_XCHG_DRIVERS_SUPPORT   0
#define CFG_GLOBAL_EEMBC_NET_SUPPORT   0
#define CFG_GLOBAL_EEMBC_DEN_SUPPORT   0
#define CFG_GLOBAL_EEMBC_JAVA_SUPPORT   0
#define CFG_GLOBAL_JAVA_SUPPORT   0
#define CFG_GLOBAL_ALSA_VOLUME_SUPPORT   0
#define CFG_GLOBAL_HOTKEY_SUPPORT   0
#define CFG_GLOBAL_BTE_SUPPORT   0
#define CFG_GLOBAL_PRIV_WMDRM_SUPPORT   0
#define CFG_GLOBAL_WIRED_ENET_SUPPORT   0
#define CFG_GLOBAL_TOUCHSCREEN_SUPPORT   0
#define CFG_GLOBAL_RTLSIM_SUPPORT   0
#define CFG_GLOBAL_VDEC_SUPPORT   0
#define CFG_GLOBAL_VDEC_DEMO_SUPPORT   0
#define CFG_GLOBAL_VDEC_TOOL_SUPPORT   0
#define CFG_GLOBAL_VC03_B0_MPHI_MINI   0
#define CFG_GLOBAL_VPMSCALED_SUPPORT   0
#define CFG_GLOBAL_VPMINTSTRESS_SUPPORT   0
#define CFG_GLOBAL_BROADWARE_NRT_SUPPORT   0
#define CFG_GLOBAL_FSTESTS_SUPPORT   0
#define CFG_GLOBAL_PTH_SUPPORT   0
#define CFG_GLOBAL_ECLIPSE_DBG_SUPPORT   0
#define CFG_GLOBAL_LDX_SUPPORT   0
#define CFG_GLOBAL_FEC_SUPPORT   0
#define CFG_GLOBAL_ECAN_TEST_SUPPORT   0
#define CFG_GLOBAL_VCP_SUPPORT   0
#define CFG_GLOBAL_VCP_VC03_DRIVER   0
#define CFG_GLOBAL_KERNEL_DEBUG_SUPPORT   0
#define CFG_GLOBAL_ROOT_FILE_SYSTEM   JFFS2_RFS
#define CFG_GLOBAL_ROOT_FILE_SYSTEM_READ_ONLY   0
#define CFG_GLOBAL_FILE_SYSTEM_JFFS2   1
#define CFG_GLOBAL_FILE_SYSTEM_CRAMFS   1
#define CFG_GLOBAL_FILE_SYSTEM_INITRAMFS   0
#define CFG_GLOBAL_NFSROOT_STRING   ""
#define CFG_GLOBAL_FILE_SYSTEM_UBIFS   0
#define CFG_GLOBAL_JFFS2_SUMMARY_SUPPORT   0
#define CFG_GLOBAL_UIMAGE_SUPPORT   0
#define CFG_GLOBAL_PAD_ROOTFS_SIZE   0
#define CFG_GLOBAL_CURL_SUPPORT   0
#define CFG_GLOBAL_LIBICONV_SUPPORT   0
#define CFG_GLOBAL_GETTEXT_SUPPORT   0
#define CFG_GLOBAL_GLIB_SUPPORT   0
#define CFG_GLOBAL_ZLIB_SUPPORT   0
#define CFG_GLOBAL_FREETYPE_SUPPORT   0
#define CFG_GLOBAL_LIBXML2_SUPPORT   0
#define CFG_GLOBAL_FONTCONFIG_SUPPORT   0
#define CFG_GLOBAL_ATK_SUPPORT   0
#define CFG_GLOBAL_LIBPNG_SUPPORT   0
#define CFG_GLOBAL_DIRECTFB_SUPPORT   0
#define CFG_GLOBAL_DIRECTFB_EXAMPLES_SUPPORT   0
#define CFG_GLOBAL_DIRECTFB_FUSION_SUPPORT   0
#define CFG_GLOBAL_CAIRO_SUPPORT   0
#define CFG_GLOBAL_PANGO_SUPPORT   0
#define CFG_GLOBAL_GTK_SUPPORT   0
#define CFG_GLOBAL_READLINE_SUPPORT   0
#define CFG_GLOBAL_SQLITE_SUPPORT   0
#define CFG_GLOBAL_LIBGPG_EEROR_SUPPORT   0
#define CFG_GLOBAL_LIBGCRYPT_SUPPORT   0
#define CFG_GLOBAL_LIBXSLT_SUPPORT   0
#define CFG_GLOBAL_ICU_SUPPORT   0
#define CFG_GLOBAL_WEBKIT_SUPPORT   0
#define CFG_GLOBAL_BUILD_LOCAL_DIRECTFB   0
#define CFG_GLOBAL_BUILD_LOCAL_DEBUG   0
#define CFG_GLOBAL_CHIP_FAMILY   CFG_GLOBAL_CHIP_FAMILY_NONE
#define CFG_GLOBAL_TOOLCHAIN_VERSION   WRL3
#define CFG_GLOBAL_LIBC_VERSION   glibc_small
#define CFG_GLOBAL_IPV6_SUPPORT   0
#define CFG_GLOBAL_IPERF_SUPPORT   0
#define CFG_GLOBAL_EMQBIT_BENCH_SUPPORT   0
#define CFG_GLOBAL_VDECAL_SUPPORT   0
#define CFG_GLOBAL_ADEC_SUPPORT   0
#define CFG_GLOBAL_ADECAL_SUPPORT   0
#define CFG_GLOBAL_DISPMANX_TESTER_SUPPORT   0
#define CFG_GLOBAL_LIBEDIT_SUPPORT   0
#define CFG_GLOBAL_LIBNCURSES_SUPPORT   0
#define CFG_GLOBAL_LIBTINFO_SUPPORT   0
#define CFG_GLOBAL_KERNEL_VARIANT   0
#define CFG_GLOBAL_KHRONOS_SAMPLE_APPS_SUPPORT   0
#define CFG_GLOBAL_VIDEO_2D_DEMO_APP_SUPPORT   0
#define CFG_GLOBAL_FUSE_SUPPORT   0
#define CFG_GLOBAL_BCMRING_HW_CRYPTO_SUPPORT   0
#define CFG_GLOBAL_SUSPEND_TO_RAM_SUPPORT   0
#define CFG_GLOBAL_MTDUTIL_TARGET_SUPPORT   0
#define CFG_GLOBAL_FLOAT_INTERCEPT   0
#define CFG_GLOBAL_FLOAT_PERF   0
#define CFG_GLOBAL_EVERY_SUPPORT   0
#define CFG_GLOBAL_ADD_TAR_TO_FS  
#define CFG_GLOBAL_OPROFILE_SUPPORT   0
#define CFG_GLOBAL_RTC_SUPPORT   0
#define CFG_GLOBAL_CSX_SUPPORT   0
#define CFG_GLOBAL_HTOP_SUPPORT   0
#define CFG_GLOBAL_BSC_SUPPORT   0
#define CFG_GLOBAL_GVR_SUPPORT   0
#define CFG_GLOBAL_EPTRPC_SUPPORT   0
#define CFG_GLOBAL_EPT_SUPPORT   0
#define CFG_GLOBAL_EPT_WB_VOICE_DEVICES   2
#define CFG_GLOBAL_EPT_NB_VOICE_DEVICES   1
#define CFG_GLOBAL_EPT_VIDEO_DEVICES   0
#define CFG_GLOBAL_PARTITION   PARTITION_A01
#define CFG_GLOBAL_MIC_CAL_APP_SUPPORT   0
#define CFG_GLOBAL_DROPBEAR_SUPPORT   0
#define CFG_GLOBAL_ETH_LED_TEST_SUPPORT   0
#define CFG_GLOBAL_FLAT_FILE_SUPPORT   0
#define CFG_GLOBAL_BOOT1_POST_SUPPORT   0
#define CFG_GLOBAL_BOOT2_POST_SUPPORT   0
#define CFG_GLOBAL_LCD_USES_PIFHW   0
#define CFG_GLOBAL_PCSC_SUPPORT   0
#define CFG_GLOBAL_VOIP_MAX_PACKET_SIZE   100000
#define CFG_GLOBAL_AUDIO_SUPPORT_TOOLS_SUPPORT   0
#define CFG_GLOBAL_AUDIOTEST_SUPPORT   0
#define CFG_GLOBAL_VOCODER_TEST_SUPPORT   0
#define CFG_GLOBAL_BBL_IS_ENABLED   0
#define CFG_GLOBAL_BCM_BOOT_REL_FILES   ""
#define CFG_GLOBAL_BCM_VCEB_REL_FILES   ""
#define CFG_GLOBAL_BCM_VMCS_REL_FILES   ""
#define CFG_GLOBAL_BCM_VMCS_ROOTFS   0
#define CFG_GLOBAL_BELLAGIO_SUPPORT   0
#define CFG_GLOBAL_BLUETOOTH_SUPPORT   0
#define CFG_GLOBAL_BOINGO_SUPPORT   0
#define CFG_GLOBAL_BOOT_WATCHDOG_SUPPORT   0
#define CFG_GLOBAL_BTPI_TEST_SUPPORT   0
#define CFG_GLOBAL_CHIP   ""
#define CFG_GLOBAL_CPU   ""
#define CFG_GLOBAL_CPU_ENDIAN   ""
#define CFG_GLOBAL_ECAN_USE_SBAEC   0
#define CFG_GLOBAL_ENABLE_POWER_SAVINGS_MODE   0
#define CFG_GLOBAL_EPT_INBAND_TONE_ENABLE   0
#define CFG_GLOBAL_GE_TEST_SUPPORT   0
#define CFG_GLOBAL_GUI_DIRS   0
#define CFG_GLOBAL_GUI_SUPPORT   0
#define CFG_GLOBAL_HOOKSWITCH_SUPPORT   0
#define CFG_GLOBAL_IPTABLES_SUPPORT   0
#define CFG_GLOBAL_LCD_SIZE   ""
#define CFG_GLOBAL_LDXKO_DIR_FOR_HAUSWARE_LIBS   0
#define CFG_GLOBAL_LDXKO_DIR_FOR_SUPPORT_LIBS   0
#define CFG_GLOBAL_LLDP_SUPPORT   0
#define CFG_GLOBAL_MPEG4_SUPPORT   0
#define CFG_GLOBAL_ONEPHONE_APP_SUPPORT   0
#define CFG_GLOBAL_PHONE_APP_SUPPORT   0
#define CFG_GLOBAL_RECONFIG_SUPPORT   0
#define CFG_GLOBAL_REDUNDANCY_SUPPORT   0
#define CFG_GLOBAL_SDC_CACHE_PAGE_SIZE   0
#define CFG_GLOBAL_SDC_ENABLE   0
#define CFG_GLOBAL_SDC_LOCATION   0
#define CFG_GLOBAL_SDC_PKA_PRIVATE_KEY1   0
#define CFG_GLOBAL_SDC_PKA_PRIVATE_KEY2   0
#define CFG_GLOBAL_SDC_PKA_PRIVATE_KEY3   0
#define CFG_GLOBAL_SDC_PKA_PRIVATE_KEY4   0
#define CFG_GLOBAL_SDC_SIZE   0
#define CFG_GLOBAL_SIMPLESIPPHONE_APP_SUPPORT   0
#define CFG_GLOBAL_SIP_SUPPORT   0
#define CFG_GLOBAL_SKYPE_SUPPORT   0
#define CFG_GLOBAL_SKYPE_VERSION   ""
#define CFG_GLOBAL_STRESSTEST_SUPPORT   0
#define CFG_GLOBAL_STUN_CLIENT   0
#define CFG_GLOBAL_SW_VERSION   ""
#define CFG_GLOBAL_TR69_SUPPORT   0
#define CFG_GLOBAL_VCHIQ_SUPPORT    0
#define CFG_GLOBAL_VIBRATOR_SUPPORT   0
#define CFG_GLOBAL_VIDEOCORE_GENERATION   ""
#define CFG_GLOBAL_VIDEOCORE_PLATFORM   ""
#define CFG_GLOBAL_VIDEOCORE_RELEASE   0
#define CFG_GLOBAL_VIDEOCORE_SDCARD_SUPPORT   0
#define CFG_GLOBAL_VIDEOCORE_TARGET   ""
#define CFG_GLOBAL_VIDEOCORE_TEST_SUPPORT   0
#define CFG_GLOBAL_VIDEO_SPLASH   ""
#define CFG_GLOBAL_WEBCONFIG_SUPPORT   0
#define CFG_GLOBAL_KHRONOS_THIRD_PARTY_APPS_SUPPORT   0

/* Configuration from /home/ljj/work/scl8500/589x_Linux_4.4a_SDK/work/linux/target/configs/overrides/chips/BCM5892/boards/BCM95892//../../config.mk */
#undef CFG_GLOBAL_CHIP                       
#undef CFG_GLOBAL_CPU                        
#undef CFG_GLOBAL_CPU_ENDIAN                 
#undef CFG_GLOBAL_DLF_SUPPORT                
#undef CFG_GLOBAL_BRCM_BOOT12_SUPPORT        
#undef CFG_GLOBAL_FILE_SYSTEM_JFFS2	
#undef CFG_GLOBAL_FILE_SYSTEM_CRAMFS	
#undef CFG_GLOBAL_BCM5892_CRYPTO_HW_SUPPORT 
#undef CFG_GLOBAL_OPENSSL_SUPPORT 
#undef CFG_GLOBAL_OPENSSL_TEST_CORE 
#undef CFG_GLOBAL_UBI_SUPPORT 
#undef CFG_GLOBAL_HACKBENCH_SUPPORT 
#undef CFG_GLOBAL_MULTICAST_SENDER_SUPPORT 
#undef CFG_GLOBAL_MULTICAST_RECEIVER_SUPPORT 
#undef CFG_GLOBAL_ETHTOOL_SUPPORT 
#undef CFG_GLOBAL_WIRELESSTOOLS_SUPPORT 
#undef CFG_GLOBAL_DHD_ROMTERM_SUPPORT 
#undef CFG_GLOBAL_DHD_NVRAM_TXT 
#define CFG_GLOBAL_CHIP                         BCM5892
#define CFG_GLOBAL_CPU                          ARM11
#define CFG_GLOBAL_CPU_ENDIAN                   le
#define CFG_GLOBAL_DLF_SUPPORT                  0
#define CFG_GLOBAL_BRCM_BOOT12_SUPPORT          0
#define CFG_GLOBAL_FILE_SYSTEM_JFFS2	  1
#define CFG_GLOBAL_FILE_SYSTEM_CRAMFS	  0
#define CFG_GLOBAL_BCM5892_CRYPTO_HW_SUPPORT   1
#define CFG_GLOBAL_OPENSSL_SUPPORT   1
#define CFG_GLOBAL_OPENSSL_TEST_CORE   1
#define CFG_GLOBAL_UBI_SUPPORT   1
#define CFG_GLOBAL_HACKBENCH_SUPPORT   1
#define CFG_GLOBAL_MULTICAST_SENDER_SUPPORT   1
#define CFG_GLOBAL_MULTICAST_RECEIVER_SUPPORT   1
#define CFG_GLOBAL_ETHTOOL_SUPPORT   1
#define CFG_GLOBAL_WIRELESSTOOLS_SUPPORT   1
#define CFG_GLOBAL_DHD_ROMTERM_SUPPORT   1
#define CFG_GLOBAL_DHD_NVRAM_TXT   wl-nvram.txt

/* Configuration from /home/ljj/work/scl8500/589x_Linux_4.4a_SDK/work/linux/target/configs/overrides/chips/BCM5892/boards/BCM95892/config.mk */
#undef CFG_GLOBAL_UIMAGE_SUPPORT             
#undef CFG_GLOBAL_RAM_BASE			
#undef CFG_GLOBAL_FBCTL_SUPPORT 
#undef CFG_GLOBAL_FBBMP_SUPPORT 
#undef CFG_GLOBAL_VDEC_SUPPORT 
#undef CFG_GLOBAL_VDEC_TOOL_SUPPORT 
#undef CFG_GLOBAL_LINUX_RAM_SIZE 
#undef CFG_GLOBAL_KERNEL_DEBUG_SUPPORT	
#undef CFG_GLOBAL_ALSA_LIB_SUPPORT      
#undef CFG_GLOBAL_ALSA_UTIL_SUPPORT     
#undef CFG_GLOBAL_HALAUDIO_SUPPORT      
#undef CFG_GLOBAL_HALAUDIO_ALSA_SUPPORT 
#undef CFG_GLOBAL_BACKLIGHT_SUPPORT 
#undef CFG_GLOBAL_BLCTL_SUPPORT 
#undef CFG_GLOBAL_PCSC_SUPPORT  
#undef CFG_GLOBAL_FAAD2_SUPPORT 
#undef CFG_GLOBAL_LINUX_VERSION 
#undef CFG_GLOBAL_UDEV_SUPPORT 
#undef CFG_GLOBAL_OPROFILE_SUPPORT 
#define CFG_GLOBAL_UIMAGE_SUPPORT               0
#define CFG_GLOBAL_RAM_BASE			  0x40000000
#define CFG_GLOBAL_FBCTL_SUPPORT   1
#define CFG_GLOBAL_FBBMP_SUPPORT   1
#define CFG_GLOBAL_VDEC_SUPPORT   1
#define CFG_GLOBAL_VDEC_TOOL_SUPPORT   1
#define CFG_GLOBAL_LINUX_RAM_SIZE   0x8000000
#define CFG_GLOBAL_KERNEL_DEBUG_SUPPORT	  1
#define CFG_GLOBAL_ALSA_LIB_SUPPORT        1
#define CFG_GLOBAL_ALSA_UTIL_SUPPORT       1
#define CFG_GLOBAL_HALAUDIO_SUPPORT        0
#define CFG_GLOBAL_HALAUDIO_ALSA_SUPPORT   0
#define CFG_GLOBAL_BACKLIGHT_SUPPORT   0
#define CFG_GLOBAL_BLCTL_SUPPORT   0
#define CFG_GLOBAL_PCSC_SUPPORT    1
#define CFG_GLOBAL_FAAD2_SUPPORT   1
#define CFG_GLOBAL_LINUX_VERSION   linux-2.6.32.9
#define CFG_GLOBAL_UDEV_SUPPORT   0
#define CFG_GLOBAL_OPROFILE_SUPPORT   0

/* Configuration from /home/ljj/work/scl8500/589x_Linux_4.4a_SDK/work/projects/bcm589x/build/config.mk */
#undef LINUX_BOARD_DIR 
#undef CFG_GLOBAL_DRIVER_TEST_SUPPORT 
#undef CFG_GLOBAL_SERIAL_TEST_SUPPORT 
#undef CFG_GLOBAL_DEBUG_TEST_SUPPORT 
#undef CFG_GLOBAL_MTDUTIL_TARGET_SUPPORT 
#define LINUX_BOARD_DIR   $(wildcard $(addsuffix /boards/$(BOARD),$(BCMFAMILIES)))
#define CFG_GLOBAL_DRIVER_TEST_SUPPORT   1
#define CFG_GLOBAL_SERIAL_TEST_SUPPORT   1
#define CFG_GLOBAL_DEBUG_TEST_SUPPORT   1
#define CFG_GLOBAL_MTDUTIL_TARGET_SUPPORT   1

/* Configuration from /home/ljj/work/scl8500/589x_Linux_4.4a_SDK/work/projects/bcm589x/build/secuapp/custom/config.mk */
#undef CFG_GLOBAL_ROOT_FILE_SYSTEM 
#undef CFG_GLOBAL_KERNEL_DEBUG_SUPPORT       
#undef CFG_GLOBAL_MICROWIN_SUPPORT           
#undef CFG_GLOBAL_SHOW_SUPPORT               
#undef CFG_GLOBAL_OTA_ENABLE                 
#undef CFG_GLOBAL_TCPDUMP_SUPPORT            
#undef CFG_GLOBAL_STRACE_SUPPORT             
#undef CFG_GLOBAL_NTP_SUPPORT                
#undef CFG_GLOBAL_LIBRT_SUPPORT              
#undef CFG_GLOBAL_TOOLCHAIN_VERSION		
#define CFG_GLOBAL_ROOT_FILE_SYSTEM   INITRAMFS
#define CFG_GLOBAL_KERNEL_DEBUG_SUPPORT         1
#define CFG_GLOBAL_MICROWIN_SUPPORT             0
#define CFG_GLOBAL_SHOW_SUPPORT                 0
#define CFG_GLOBAL_OTA_ENABLE                   0
#define CFG_GLOBAL_TCPDUMP_SUPPORT              1
#define CFG_GLOBAL_STRACE_SUPPORT               0
#define CFG_GLOBAL_NTP_SUPPORT                  0
#define CFG_GLOBAL_LIBRT_SUPPORT                1
#define CFG_GLOBAL_TOOLCHAIN_VERSION		  buildroot-20080513

#endif /* _CFG_GLOBAL_H_ */
