EXTRA_CFLAGS := -Werror

obj-$(CONFIG_BCM_CSX)               += csx_framework/
obj-$(CONFIG_BCM_CSX_GIST)          += csx_gist/
obj-$(CONFIG_BCM_CSX_HALAUDIO)      += csx_halaudio/
obj-$(CONFIG_BCM_CSX_SIGMORPH)      += csx_sigmorph/
