#
# Makefile which builds BCMRING drivers
#

EXTRA_CFLAGS := -Werror

obj-$(CONFIG_BCM_LCD_BACKLIGHT)  += lcd_backlight.o
obj-$(CONFIG_MM_DMA)             += mmdma.o
obj-$(CONFIG_BCMRING_GEV3)       += bcmring_gev3.o
obj-$(CONFIG_BCMRING_LCD)        += bcmring_lcd.o
obj-$(CONFIG_BCMRING_VPM)        += bcmring_vpm.o
obj-$(CONFIG_NET_BCMRING)        += bcmring_esw.o
obj-$(CONFIG_BCMRING_ETH_LED)    += bcmring_eth_led.o
obj-$(CONFIG_BCMRING_GPS)    	 += bcmring_gps.o
