# Display drivers

display-objs				:= display-sysfs.o

obj-$(CONFIG_DISPLAY_SUPPORT)		+= display.o

obj-$(CONFIG_DISPLAY_LGP_LB040Q03)	+= display-lgp-LB040Q03.o
obj-$(CONFIG_DISPLAY_BCMRING_GENERIC) += display-bcmring-generic.o
