#
# Makefile for bcm5892  
#

# Object file lists.
obj-y 	:= arch.o irq.o time.o clock.o
obj-y	+= pm.o 
obj-y   += pmb.o 
obj-y   += shm.o
obj-y   += pl080-dma.o
obj-y	+= strong_lion_proc.o

EXTRA_CFLAGS += -Iarch/arm/mach-bcm5892/hw_cfg -Ihw_cfg

