#
## Makefile for ALSA BROADCOM 5892
#
#
EXTRA_CFLAGS := -Wno-error

obj-m += snd-bcm5892.o
snd-bcm5892-objs := bcm5892_alsa_dev.o bcm5892_alsa_pcm.o bcm5892_alsa_i2s.o
snd-bcm5892-objs += bcm5892_alsa_ctl.o bcm5892_alsa_i2c.o bcm5892_alsa_codec.o


